services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL : ${DATABASE_URL}
    image: remix-start:latest
    container_name: remix-start
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}