FROM node:23-bullseye-slim AS base

ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"
ENV SHELL="/bin/sh"
RUN apt-get update && apt-get install -y openssl
RUN npm install --global pnpm@latest

FROM base AS deps
WORKDIR /app
COPY .npmrc ./
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY prisma ./prisma
RUN pnpm install

FROM deps AS dev-deps
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm install --frozen-lockfile

FROM base AS dev-runner

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
ENV PORT=5173
EXPOSE 5173
ENV NODE_ENV="development"

WORKDIR /app

COPY --from=dev-deps /app/package.json ./
COPY --from=dev-deps /app/pnpm-lock.yaml ./
COPY --from=dev-deps /app/node_modules ./node_modules
COPY --from=dev-deps /app/prisma ./prisma
COPY --from=dev-deps /app ./

VOLUME ["/app/node_modules"]
VOLUME ["/app"]

ENTRYPOINT [ "sh", "-c", "npm run dev -- --host 0.0.0.0" ]